import type {Metadata} from 'next'
import {Philosopher} from 'next/font/google'
import Header from './components/Header'
import './globals.css'
import {Bona_Nova} from "next/font/google";

const philosopher = Philosopher({
    subsets: ['latin'],
    weight: ['400', '700'],
    display: 'swap',
})

const bona_nova = Bona_Nova({
    subsets: ['latin'],
    weight: ['400', '700'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: 'Слово',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='ru'>
        <body>
        <div className={philosopher.className}>
            <Header/>
        </div>
        <div className={bona_nova.className}>
            {children}
        </div>
        </body>
        </html>
    )
}
