import type {Metadata} from "next";
import {Philosopher} from "next/font/google";
import "./globals.css";

const philosopher = Philosopher({
    subsets: ["latin"],
    weight: ['400', '700'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: "Слово",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
        <body className={philosopher.className}>{children}</body>
        </html>
    );
}
